name: "mena_engine"
platform: "tensorrt_plan"
max_batch_size: 0
input [
 {
    name: "input"
    data_type: TYPE_FP32
    format: FORMAT_NONE
    dims: [1, 3, 64, 160]
  }
]
output [{
    name: "output"
    data_type: TYPE_FP32
    dims: [1, 38, 37]
  },
  {
    name: "cls"
    data_type: TYPE_FP32
    dims: [1, 13]
  }
]

